# Generated by Django 4.2.30 on 2026-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('variation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variation_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('open_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ticker', '-timestamp'], name='market_data_ticker_b4522f_idx')],
            },
        ),
    ]
