# Generated by Django 4.2.30 on 2026-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='B3CorporateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('DIVIDENDO', 'Dividendo'), ('JRS', 'Juros'), ('SPLIT', 'Split'), ('GRUP', 'Grouping'), ('BONUS', 'Bonus'), ('RED', 'Rights')], max_length=20)),
                ('event_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='B3StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('high', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('low', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=18)),
                ('volume', models.BigIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['ticker', '-date'], name='market_data_ticker_cff62d_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='B3Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('close', models.DecimalField(decimal_places=2, max_digits=18)),
                ('variation', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('variation_pct', models.DecimalField(decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['symbol', '-date'], name='market_data_symbol_8d8ccd_idx')],
            },
        ),
    ]
