from django.urls import path
from .views import (
    PortfolioSummaryView,
    InstitutionListCreateView,
    AssetListCreateView,
    InvestmentAccountListCreateView,
    PositionListCreateView,
    TransactionListCreateView,
    GoalListCreateView,
    NotificationListView,
    NotificationMarkReadView,
    ImportPositionsView,
    ImportTemplateView,
    ImportPreviewView,
    RebalanceView,
    BenchmarkView,
    InsightsView,
    SimulatorView,
    AllocationAnalysisView,
    RebalanceSuggestionView,
    ConcentrationRiskView,
    PortfolioHealthScoreView,
    RiskByClassView,
    VolatilityView,
    CorrelationView,
    DrawdownView,
    MaturityAlertsView,
    TaxesCalculatorView,
    TaxReportView,
    TaxCalculationView,
    DARFGenerationView,
    DARFPaymentView,
    TaxLotManagementView,
    OpportunityAlertsView,
    MarketOpportunitiesView,
    CampaignView,
    ReconciliationIssueListView,
    ReconciliationIssueResolveView,
    RunReconciliationView,
    CorporateActionListCreateView,
    ProfitabilityReportView,
    GenerateReportView,
    BackupExportView,
    PortfolioSnapshotView,
    PortfolioSnapshotDetailView,
    GenerateSnapshotView
)

urlpatterns = [
    path('summary/', PortfolioSummaryView.as_view(), name='portfolio_summary'),
    path('institutions/', InstitutionListCreateView.as_view(), name='institutions'),
    path('assets/', AssetListCreateView.as_view(), name='assets'),
    path('accounts/', InvestmentAccountListCreateView.as_view(), name='accounts'),
    path('positions/', PositionListCreateView.as_view(), name='positions'),
    path('transactions/', TransactionListCreateView.as_view(), name='transactions'),
    path('goals/', GoalListCreateView.as_view(), name='goals'),
    path('notifications/', NotificationListView.as_view(), name='notifications'),
    path('notifications/mark-read/', NotificationMarkReadView.as_view(), name='notifications_mark_read'),
    path('positions/import/', ImportPositionsView.as_view(), name='import_positions'),
    path('positions/import/template/', ImportTemplateView.as_view(), name='import_template'),
    path('positions/import/preview/', ImportPreviewView.as_view(), name='import_preview'),
    path('rebalance/', RebalanceView.as_view(), name='rebalance'),
    path('benchmark/', BenchmarkView.as_view(), name='benchmark'),
    path('insights/', InsightsView.as_view(), name='insights'),
    path('simulator/', SimulatorView.as_view(), name='simulator'),
    path('allocation/', AllocationAnalysisView.as_view(), name='allocation'),
    path('rebalance-suggestion/', RebalanceSuggestionView.as_view(), name='rebalance_suggestion'),
    path('concentration/', ConcentrationRiskView.as_view(), name='concentration'),
    path('health-score/', PortfolioHealthScoreView.as_view(), name='health_score'),
    path('risk-by-class/', RiskByClassView.as_view(), name='risk_by_class'),
    path('volatility/', VolatilityView.as_view(), name='volatility'),
    path('correlation/', CorrelationView.as_view(), name='correlation'),
    path('drawdown/', DrawdownView.as_view(), name='drawdown'),
    path('maturity-alerts/', MaturityAlertsView.as_view(), name='maturity_alerts'),
    path('taxes/', TaxesCalculatorView.as_view(), name='taxes'),
    path('tax-report/', TaxReportView.as_view(), name='tax_report'),
    path('tax/calculate/', TaxCalculationView.as_view(), name='tax_calculate'),
    path('tax/darf/', DARFGenerationView.as_view(), name='tax_darf'),
    path('tax/darf/pay/', DARFPaymentView.as_view(), name='tax_darf_pay'),
    path('tax/lots/', TaxLotManagementView.as_view(), name='tax_lots'),
    path('opportunities/', OpportunityAlertsView.as_view(), name='opportunities'),
    path('market-opportunities/', MarketOpportunitiesView.as_view(), name='market_opportunities'),
    path('campaigns/', CampaignView.as_view(), name='campaigns'),
    path('reconciliation/', ReconciliationIssueListView.as_view(), name='reconciliation'),
    path('reconciliation/<int:pk>/', ReconciliationIssueResolveView.as_view(), name='reconciliation_resolve'),
    path('reconciliation/run/', RunReconciliationView.as_view(), name='run_reconciliation'),
    path('corporate-actions/', CorporateActionListCreateView.as_view(), name='corporate_actions'),
    path('reports/profitability/', ProfitabilityReportView.as_view(), name='profitability_report'),
    path('reports/generate/', GenerateReportView.as_view(), name='generate_report'),
    path('backup/export/', BackupExportView.as_view(), name='backup_export'),
    path('snapshots/', PortfolioSnapshotView.as_view(), name='snapshots'),
    path('snapshots/<int:pk>/', PortfolioSnapshotDetailView.as_view(), name='snapshot_detail'),
    path('snapshots/generate/', GenerateSnapshotView.as_view(), name='generate_snapshot'),
]
