# Generated by Django 4.2.30 on 2026-04-12 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_name', models.CharField(max_length=50)),
                ('broker_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONNECTED', 'Conectado'), ('ERROR', 'Erro'), ('DISABLED', 'Desativado')], default='PENDING', max_length=20)),
                ('api_key', models.CharField(blank=True, help_text='Criptografado', max_length=200)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'broker_code')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=20)),
                ('positions_synced', models.IntegerField(default=0)),
                ('transactions_synced', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='automations.brokerconnection')),
            ],
            options={
                'ordering': ['-sync_date'],
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('PRICE_ABOVE', 'Preco acima de'), ('PRICE_BELOW', 'Preco abaixo de'), ('PROFIT_ABOVE', 'Lucro acima de %'), ('PROFIT_BELOW', 'Prejuizo acima de %'), ('PORTFOLIO_VALUE', 'Valor da carteira'), ('DAILY_CONTRIBUTION', 'Aporte diario'), ('GOAL_PROGRESS', 'Progresso da meta')], max_length=20)),
                ('condition_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('asset_ticker', models.CharField(blank=True, help_text='Se vazio, aplica a todos', max_length=20, null=True)),
                ('action_type', models.CharField(choices=[('NOTIFY', 'Notificacao'), ('ALERT', 'Alerta'), ('REBALANCE', 'Sugerir rebalanceamento'), ('CONTRIBUTION', 'Sugerir aporte')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_triggers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('condition_met', models.BooleanField()),
                ('action_taken', models.CharField(blank=True, max_length=100)),
                ('details', models.TextField(blank=True)),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.automationtrigger')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
