# Generated by Django 4.2.30 on 2026-04-17 17:49

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pb_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ev_ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('divida_ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crescimento_lucro', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('margem_liquida', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('crescimento_receita', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('score_dy', models.IntegerField(blank=True, null=True)),
                ('score_pe', models.IntegerField(blank=True, null=True)),
                ('score_pb', models.IntegerField(blank=True, null=True)),
                ('score_roe', models.IntegerField(blank=True, null=True)),
                ('score_divida', models.IntegerField(blank=True, null=True)),
                ('score_crescimento', models.IntegerField(blank=True, null=True)),
                ('score_total', models.IntegerField()),
                ('classificacao', models.CharField(choices=[('EXCELENTE', 'Excelente'), ('BOM', 'Bom'), ('NEUTRO', 'Neutro'), ('RUIM', 'Ruim'), ('MUITO_RUIM', 'Muito Ruim')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-score_total'],
                'indexes': [models.Index(fields=['ticker', '-date'], name='intelligenc_ticker_377596_idx'), models.Index(fields=['classificacao', '-date'], name='intelligenc_classif_ede1eb_idx'), models.Index(fields=['score_total', '-date'], name='intelligenc_score_t_410d5b_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Projecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=18)),
                ('aporte_mensal', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('taxa_retorno', models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Taxa anual em formato decimal (ex: 0.10 para 10%)', max_digits=10)),
                ('horizonte_meses', models.IntegerField(help_text='Horizonte em meses')),
                ('taxa_retorno_bullish', models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=10)),
                ('taxa_retorno_bearish', models.DecimalField(decimal_places=4, default=Decimal('-0.10'), max_digits=10)),
                ('resultado_base', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('resultado_bullish', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('resultado_bearish', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('resultado_conservador', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('resultado_otimista', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('cenarios', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projecoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('list_type', models.CharField(choices=[('FAVORITOS', 'Favoritos'), ('BAZIN', 'Na Esteira Bazin'), ('GRAHAM', 'Magnata Graham'), ('GARP', 'Crescimento'), ('CUSTOM', 'Personalizada')], default='CUSTOM', max_length=20)),
                ('tickers', models.JSONField(default=list, help_text='Lista de tickers')),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
