# Generated by Django 4.2.30 on 2026-04-11 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(help_text='Ex: PETR4', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Petróleo Brasileiro S.A.', max_length=100)),
                ('asset_type', models.CharField(choices=[('ACAO', 'Ação (RV)'), ('FII', 'Fundo Imobiliário'), ('RF', 'Renda Fixa'), ('TESOURO', 'Tesouro Direto'), ('CRIPTO', 'Criptomoeda'), ('FUNDO', 'Fundo de Investimento')], max_length=30)),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_id', models.CharField(blank=True, help_text='Mapping ID for Open Finance', max_length=50, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, help_text='Ex: Minha Conta XP', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolio.institution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'institution', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Médio')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Atual')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolio.investmentaccount')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='portfolio.asset')),
            ],
        ),
    ]
