# Generated by Django 4.2.30 on 2026-04-12 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='currency',
            field=models.CharField(default='BRL', max_length=3),
        ),
        migrations.AddField(
            model_name='asset',
            name='is_international',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('ACAO', 'Ação (RV)'), ('FII', 'Fundo Imobiliário'), ('ETF', 'ETF'), ('RF', 'Renda Fixa'), ('TESOURO', 'Tesouro Direto'), ('CRIPTO', 'Criptomoeda'), ('FUNDO', 'Fundo de Investimento'), ('PREVIDENCIA', 'Previdência Privada')], max_length=30),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(help_text='Petroleo Brasileiro S.A.', max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='average_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preco Medio'),
        ),
        migrations.AlterField(
            model_name='position',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preco Atual'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('COMPRA', 'Compra'), ('VENDA', 'Venda'), ('APORTE', 'Aporte'), ('RESGATE', 'Resgate'), ('DIVIDENDO', 'Dividendo/Juros'), ('AMORTIZACAO', 'Amortizacao'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.investmentaccount')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='portfolio.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('ALERT', 'Alerta'), ('INFO', 'Informacao'), ('WARNING', 'Aviso'), ('SUCCESS', 'Sucesso')], default='INFO', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goal_type', models.CharField(choices=[('APOSENTADORIA', 'Aposentadoria'), ('IMOVEL', 'Compra de Imovel'), ('VIAGEM', 'Viagem'), ('EDUCACAO', 'Educacao'), ('EMERGENCIA', 'Reserva de Emergencia'), ('CRESCIMENTO', 'Crescimento Patrimonial'), ('OUTRO', 'Outro')], max_length=30)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('target_date', models.DateField()),
                ('monthly_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
