# Generated by Django 4.2.30 on 2026-04-12 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_asset_currency_asset_is_international_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('ORPHAN_POSITION', 'Posição órfã'), ('MISSING_PRICE', 'Preço faltando'), ('NEGATIVE_QUANTITY', 'Quantidade negativa'), ('DUPLICATE_POSITION', 'Posição duplicada'), ('MISSING_ASSET', 'Ativo não encontrado'), ('PRICE_MISMATCH', 'Divergência de preço')], max_length=30)),
                ('description', models.TextField()),
                ('related_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IGNORED', 'Ignorado'), ('RESOLVED', 'Resolvido')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
