# Generated by Django 4.2.30 on 2026-04-17 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0003_reconciliationissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('DIVIDENDO', 'Dividendo / JCP'), ('DESDOBRAMENTO', 'Desdobramento (Split)'), ('GRUPAMENTO', 'Grupamento (Reverse Split)'), ('BONIFICACAO', 'Bonificação'), ('AMORTIZACAO', 'Amortização')], max_length=30)),
                ('date', models.DateField()),
                ('ratio', models.DecimalField(blank=True, decimal_places=6, help_text='Ex: 2 para desdobramento 1:2. 0.5 para grupamento 2:1', max_digits=18, null=True)),
                ('amount_per_share', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPLIED', 'Aplicado'), ('CANCELLED', 'Cancelado')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='corporate_actions', to='portfolio.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
