# Generated by Django 4.2.30 on 2026-04-17 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_corporateaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Data do snapshot')),
                ('total_value', models.DecimalField(decimal_places=2, help_text='Valor total do portfólio', max_digits=18)),
                ('cash_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor em caixa', max_digits=18)),
                ('position_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor em posições', max_digits=18)),
                ('variation', models.DecimalField(decimal_places=2, default=0, help_text='Variação do período', max_digits=18)),
                ('variation_percent', models.DecimalField(decimal_places=4, default=0, help_text='Variação percentual', max_digits=10)),
                ('allocation', models.JSONField(default=dict, help_text='Alocação por classe de ativo')),
                ('positions_count', models.IntegerField(default=0, help_text='Número de posições')),
                ('accounts_count', models.IntegerField(default=0, help_text='Número de contas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
