# Generated by Django 4.2.30 on 2026-04-11 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('CONSERVADOR', 'Conservador'), ('MODERADO', 'Moderado'), ('ARROJADO', 'Arrojado')], max_length=20, null=True)),
                ('primary_broker', models.CharField(blank=True, max_length=50, null=True)),
                ('financial_goal', models.CharField(blank=True, max_length=150, null=True)),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
