# Generated by Django 4.2.30 on 2026-04-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_customuser_currency_customuser_email_notifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Usuário'), ('MANAGER', 'Gerente'), ('SUPPORT', 'Suporte'), ('ADMIN', 'Administrador')], default='USER', max_length=20),
        ),
    ]
